baseURL = 'https://byron2016.github.io/byron.dev/'
languageCode = 'en-us'
title = 'My New Hugo Site'
Theme = 'tale'

relativeURLs = true
canonifyURLs = true

[menu]
  [[menu.main]]
    identifier = "contacto"
    name = "Contacto"
    title = "Contacto"
    url = "/contacto/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Post"
    url = "/posts/"
    weight = 0